name: CI

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'Package*'
      - 'Sources/**'
      - 'Tests/**'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'Package*'
      - 'Sources/**'
      - 'Tests/**'

jobs:
  mac:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
    env:
      CX_COMBINE_IMPLEMENTATION: CombineX
    steps:
      - uses: actions/checkout@v1
      - run: swift test

  linux:
    strategy:
      fail-fast: false
      matrix:
        swift_version: ['5.1', '5.2', '5.3', 'latest']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.swift_version }}
    steps:
      - uses: actions/checkout@v1
      - run: swift test --enable-test-discovery

  combine:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
    env:
      CX_COMBINE_IMPLEMENTATION: Combine
    steps:
      - uses: actions/checkout@v1
      - run: swift test
